POST http://localhost:2001/api/users
Content-Type: application/json

{
    "name":"Bob3",
    "email":"bob3@gmail.com",
    "password":"bob3"
}

###
GET http://localhost:2001/api/users
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiIzMGE3NWJjYy0wMmY1LTQ3NDktYWZjMS0wMDQ3YmM4YjE5YzAiLCJlbWFpbCI6IkJvYiIsInBhc3N3b3JkIjoiYm9iQGdtYWlsLmNvbSJ9LCJpYXQiOjE2ODE2MzAwNTksImV4cCI6MTY4MTYzMDExOX0.vtX6e7q6I5vgaV1BZfo2_ZJEwS3YlltuprfZUlASqpw


###
POST http://localhost:2001/api/auth/login
Content-Type: application/json

{
    "email":"bob@gmail.com",
    "password":"bob"
}


###
GET http://localhost:2001/api/auth/refresh_token

###
DELETE http://localhost:2001/api/auth/refresh_token

