POST http://localhost:2001/api/users
Content-Type: application/json

{
    "name":"Bob2",
    "email":"bob2@gmail.com",
    "password":"bob2"
}

###
POST http://localhost:2001/api/auth/login
Content-Type: application/json

{
    "email":"bob@gmail.com",
    "password":"bob"
}
