POST http://localhost:2001/api/users
Content-Type: application/json

{
    "name":"y",
    "email":"y@gmail.com",
    "password":"y",
    "privileges":"",
    "genre":"",
    "city":""
}

###
GET http://localhost:2001/api/users
Content-Type: application/json
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Im5hbWUiOiIzOGFiYzI0OC03MzM5LTQzNTMtYjM4Ni02YzI4NzI1ZTMzOGQiLCJlbWFpbCI6IndpbTQiLCJwYXNzd29yZCI6IndpbTRAZ21haWwuY29tIiwicHJpdmlsZWdlcyI6ZmFsc2UsImdlbnJlIjpudWxsLCJjaXR5IjpudWxsLCJpbWciOm51bGx9LCJpYXQiOjE2ODIxMTAzMDUsImV4cCI6MTY4MjExMDYwNX0.SSOAzGTj-3pmK32UzqR-c_1lEZ1eoLCd37LamcUTy0A


###
POST http://localhost:2001/api/auth/login
Content-Type: application/json

{
    "email":"wim4@gmail.com",
    "password":"wim4"
}

###
GET http://localhost:2001/api/auth/refresh_token

###
DELETE http://localhost:2001/api/auth/refresh_token

